CREATE TABLE poi_semantic_mapping (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mapping_code VARCHAR(64) NOT NULL UNIQUE,
    display_name VARCHAR(128) NOT NULL,
    amap_type_prefixes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    keyword_patterns TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    category_group VARCHAR(64),
    interest_tag_codes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    is_classic BOOLEAN NOT NULL DEFAULT FALSE,
    is_local BOOLEAN NOT NULL DEFAULT FALSE,
    is_photo_friendly BOOLEAN NOT NULL DEFAULT FALSE,
    is_night_friendly BOOLEAN NOT NULL DEFAULT FALSE,
    is_quiet BOOLEAN NOT NULL DEFAULT FALSE,
    is_hidden_gem BOOLEAN NOT NULL DEFAULT FALSE,
    weather_sensitivity NUMERIC(3, 2) NOT NULL DEFAULT 0,
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_poi_semantic_mapping_enabled_priority
    ON poi_semantic_mapping (enabled, priority);

CREATE INDEX idx_poi_semantic_mapping_category_group
    ON poi_semantic_mapping (category_group);

INSERT INTO poi_semantic_mapping (
    mapping_code,
    display_name,
    amap_type_prefixes,
    keyword_patterns,
    category_group,
    interest_tag_codes,
    is_classic,
    is_local,
    is_photo_friendly,
    is_night_friendly,
    is_quiet,
    is_hidden_gem,
    weather_sensitivity,
    priority
)
VALUES
    (
        'SCENIC_LANDMARK',
        '经典景区与地标',
        ARRAY['1100'],
        ARRAY['景点', '公园', '地标', '广场', '观景'],
        'SCENIC',
        ARRAY['SCENIC', 'PHOTO'],
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        FALSE,
        1.00,
        10
    ),
    (
        'MUSEUM_EXHIBITION',
        '博物馆与展馆',
        ARRAY['1400'],
        ARRAY['博物馆', '展览馆', '美术馆', '纪念馆', '科技馆'],
        'CULTURE',
        ARRAY['MUSEUM', 'PHOTO'],
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        0.00,
        20
    ),
    (
        'FOOD_LOCAL',
        '本地餐饮与小吃',
        ARRAY['0500'],
        ARRAY['本地菜', '小吃', '老字号', '夜市', '美食街', '特色菜'],
        'FOOD',
        ARRAY['FOOD', 'LOCAL'],
        FALSE,
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        0.00,
        30
    ),
    (
        'COFFEE_REST',
        '咖啡甜品与休息',
        ARRAY['0505'],
        ARRAY['咖啡', '甜品', '茶馆', '书店'],
        'REST',
        ARRAY['COFFEE'],
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        0.00,
        40
    ),
    (
        'SHOPPING_DISTRICT',
        '购物商圈与步行街',
        ARRAY['0600', '0610'],
        ARRAY['商场', '购物中心', '步行街', '街区'],
        'SHOPPING',
        ARRAY['SHOPPING', 'LOCAL'],
        FALSE,
        TRUE,
        TRUE,
        TRUE,
        FALSE,
        FALSE,
        0.20,
        50
    ),
    (
        'NIGHT_MARKET_VIEW',
        '夜市夜景',
        ARRAY['0500', '1100'],
        ARRAY['夜市', '夜景', '夜游', '观景台', '酒吧街'],
        'NIGHT',
        ARRAY['NIGHT', 'FOOD', 'PHOTO'],
        FALSE,
        TRUE,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        0.70,
        60
    ),
    (
        'LOCAL_LIFE_BLOCK',
        '本地生活街区',
        ARRAY['0601', '0700'],
        ARRAY['老街', '街巷', '市集', '社区', '胡同', '弄堂'],
        'LOCAL',
        ARRAY['LOCAL', 'PHOTO'],
        FALSE,
        TRUE,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        0.60,
        70
    ),
    (
        'QUIET_PARK',
        '安静公园绿地',
        ARRAY['1101'],
        ARRAY['公园', '绿地', '湿地', '湖', '植物园'],
        'SCENIC',
        ARRAY['SCENIC'],
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        1.00,
        80
    )
ON CONFLICT (mapping_code) DO NOTHING;
