CREATE TABLE baidu_poi_semantic_mapping (
    id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
    mapping_code VARCHAR(64) NOT NULL UNIQUE,
    display_name VARCHAR(128) NOT NULL,
    baidu_primary_tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    baidu_secondary_tags TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    baidu_type_values TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    keyword_patterns TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    category_group VARCHAR(64),
    interest_tag_codes TEXT[] NOT NULL DEFAULT ARRAY[]::TEXT[],
    is_classic BOOLEAN NOT NULL DEFAULT FALSE,
    is_local BOOLEAN NOT NULL DEFAULT FALSE,
    is_photo_friendly BOOLEAN NOT NULL DEFAULT FALSE,
    is_night_friendly BOOLEAN NOT NULL DEFAULT FALSE,
    is_quiet BOOLEAN NOT NULL DEFAULT FALSE,
    is_hidden_gem BOOLEAN NOT NULL DEFAULT FALSE,
    weather_sensitivity NUMERIC(3, 2) NOT NULL DEFAULT 0,
    priority INTEGER NOT NULL DEFAULT 0,
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMPTZ NOT NULL DEFAULT now(),
    updated_at TIMESTAMPTZ NOT NULL DEFAULT now()
);

CREATE INDEX idx_baidu_poi_semantic_mapping_enabled_priority
    ON baidu_poi_semantic_mapping (enabled, priority);

CREATE INDEX idx_baidu_poi_semantic_mapping_category_group
    ON baidu_poi_semantic_mapping (category_group);

INSERT INTO baidu_poi_semantic_mapping (
    mapping_code,
    display_name,
    baidu_primary_tags,
    baidu_secondary_tags,
    baidu_type_values,
    keyword_patterns,
    category_group,
    interest_tag_codes,
    is_classic,
    is_local,
    is_photo_friendly,
    is_night_friendly,
    is_quiet,
    is_hidden_gem,
    weather_sensitivity,
    priority
)
VALUES
    (
        'BAIDU_SCENIC_LANDMARK',
        '百度经典景区与地标',
        ARRAY['旅游景点', '行政地标', '自然地物'],
        ARRAY['公园', '动物园', '植物园', '游乐园', '水族馆', '海滨浴场', '文物古迹', '教堂', '风景区', '景点', '寺庙', '商圈', '山峰', '水系'],
        ARRAY['scope'],
        ARRAY['景点', '公园', '地标', '广场', '观景', '风景区', '文物古迹', '寺庙', '教堂', '商圈'],
        'SCENIC',
        ARRAY['SCENIC', 'PHOTO'],
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        FALSE,
        1.00,
        10
    ),
    (
        'BAIDU_MUSEUM_EXHIBITION',
        '百度博物馆与展馆',
        ARRAY['旅游景点', '教育培训', '文化传媒'],
        ARRAY['博物馆', '科技馆', '图书馆', '美术馆', '展览馆', '文化宫', '新闻出版', '艺术团体'],
        ARRAY['scope', 'education', 'enterprise'],
        ARRAY['博物馆', '展览馆', '美术馆', '纪念馆', '科技馆', '图书馆', '文化宫'],
        'CULTURE',
        ARRAY['MUSEUM', 'PHOTO'],
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        0.00,
        20
    ),
    (
        'BAIDU_FOOD_LOCAL',
        '百度本地餐饮与小吃',
        ARRAY['美食'],
        ARRAY['中餐厅', '外国餐厅', '小吃快餐店', '蛋糕甜品店', '酒吧', '其他'],
        ARRAY['cater'],
        ARRAY['本地菜', '小吃', '老字号', '夜市', '美食街', '特色菜', '中餐厅', '小吃快餐店'],
        'FOOD',
        ARRAY['FOOD', 'LOCAL'],
        FALSE,
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        FALSE,
        0.00,
        30
    ),
    (
        'BAIDU_COFFEE_REST',
        '百度咖啡甜品与休息',
        ARRAY['美食'],
        ARRAY['咖啡厅', '茶座', '蛋糕甜品店'],
        ARRAY['cater'],
        ARRAY['咖啡', '咖啡厅', '甜品', '蛋糕', '茶座', '茶馆', '书店'],
        'REST',
        ARRAY['COFFEE'],
        FALSE,
        FALSE,
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        0.00,
        40
    ),
    (
        'BAIDU_SHOPPING_DISTRICT',
        '百度购物商圈与步行街',
        ARRAY['购物', '行政地标'],
        ARRAY['购物中心', '百货商场', '超市', '便利店', '商铺', '市场', '商圈'],
        ARRAY['shopping'],
        ARRAY['商场', '购物中心', '百货', '步行街', '街区', '市场', '商圈'],
        'SHOPPING',
        ARRAY['SHOPPING', 'LOCAL'],
        FALSE,
        TRUE,
        TRUE,
        TRUE,
        FALSE,
        FALSE,
        0.20,
        50
    ),
    (
        'BAIDU_NIGHT_MARKET_VIEW',
        '百度夜市夜景',
        ARRAY['美食', '旅游景点', '休闲娱乐'],
        ARRAY['酒吧', '休闲广场', '风景区', '景点', '小吃快餐店'],
        ARRAY['cater', 'scope', 'life'],
        ARRAY['夜市', '夜景', '夜游', '观景台', '酒吧街', '酒吧'],
        'NIGHT',
        ARRAY['NIGHT', 'FOOD', 'PHOTO'],
        FALSE,
        TRUE,
        TRUE,
        TRUE,
        FALSE,
        TRUE,
        0.70,
        60
    ),
    (
        'BAIDU_LOCAL_LIFE_BLOCK',
        '百度本地生活街区',
        ARRAY['生活服务', '购物', '行政地标', '房地产'],
        ARRAY['市场', '商铺', '商圈', '住宅区', '居民委员会', '公共厕所', '照相馆', '报刊亭'],
        ARRAY['life', 'shopping'],
        ARRAY['老街', '街巷', '市集', '社区', '胡同', '弄堂', '市场', '商铺', '居民区'],
        'LOCAL',
        ARRAY['LOCAL', 'PHOTO'],
        FALSE,
        TRUE,
        TRUE,
        FALSE,
        FALSE,
        TRUE,
        0.60,
        70
    ),
    (
        'BAIDU_QUIET_PARK',
        '百度安静公园绿地',
        ARRAY['旅游景点', '绿地', '自然地物'],
        ARRAY['公园', '植物园', '水系', '绿地公园', '绿化带', '湖沼', '山峰'],
        ARRAY['scope'],
        ARRAY['公园', '绿地', '湿地', '湖', '植物园'],
        'SCENIC',
        ARRAY['SCENIC'],
        FALSE,
        FALSE,
        TRUE,
        FALSE,
        TRUE,
        FALSE,
        1.00,
        80
    )
ON CONFLICT (mapping_code) DO NOTHING;

DO $$
BEGIN
    IF EXISTS (SELECT 1 FROM pg_roles WHERE rolname = 'urban_sidequest') THEN
        GRANT SELECT ON baidu_poi_semantic_mapping TO urban_sidequest;
    END IF;
END $$;
